### ISSUE TITLE
Not getting cnt value in views.py

### ISSUE THREAD

**Issue by yashwanthbabu** [imirzadeh/Django-Related-DropDowns#1]
Hi, I am using your code in my project. But when call the url, i cant get the 'cnt' value in the views. It prints the none value for me. Any suggessions please?

**Comment by imirzadeh** [comment]
May I see your code ?!
I can't tell anything unless I see the code,but I GUESS the problem is with 'url routing-url patterns' or something like this.

**Comment by yashwanthbabu** [comment]
Sorry. It's working fine now. Actually I made some changes according to my functionality and changed the code. It works fine. Thanks
